Support nonpersistent config
streamnative/mop pull request #100
Opened 2021-08-26 09:31 UTC by liangyuanpeng

#50 

Support config of non-persistent topic by default.

In my case,  some time i just use non-persistent for mop , i want my user use topic `topicA` not `non-persistent://public/default/topicA`.

2021-08-29 11:50 UTC, codelipenghui commented
@liangyepianzhou Currently, if you want to use the non-persistent topic, you can just use the non-persistent as the topic name domain such as `non-persistent://public/default/a/b/c`, the MoP will use the non-persistent topic. Does this works for you?

2021-08-29 11:53 UTC, codelipenghui commented
@liangyepianzhou Oh, sorry. I missed some context that you have mentioned in https://github.com/streamnative/mop/issues/50, the change is clear for me, but looks like there are some unrelated changes, could you please rebase/merge the master branch?

2021-08-29 14:07 UTC, liangyuanpeng commented
>  could you please rebase/merge the master branch? 

Seems like have some problem about commit log message after rebase master, i will push again later.

2021-08-31 02:48 UTC, Technoboy- commented
> > could you please rebase/merge the master branch?
> 
> Seems like have some problem about commit log message after rebase master, i will push again later.

All right. thanks.

2021-09-01 03:43 UTC, codelipenghui commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServerConfiguration.java
> +    private boolean defaultTopicPersistent = true;
It should be defaultTopicDomain = persistent, if users want to change to non-persistent, just change the defaultTopicDomain = non-persistent

2021-09-02 03:28 UTC, liangyuanpeng commented
Tested:

1. subscribe topic `helloworld3`
2. send message to topic `helloworld3`
3. consumer received message
4. topic print log   
```
23:28:04.520 [pulsar-ordered-OrderedExecutor-7-0-EventThread] INFO  org.apache.pulsar.broker.service.BrokerService - Created topic NonPersistentTopic{topic=non-persistent://public/default/helloworld3}
```

2021-09-02 04:03 UTC, codelipenghui commented
@liangyepianzhou Could you please help check the failed test? looks related to the check style, you can run ` mvn checkstyle:check && mvn license:check && mvn spotbugs:check` locally to check if there are checkstyle issues.

2021-09-02 04:26 UTC, Technoboy- commented
@liangyepianzhou 
Install [checkstyle](https://stackoverflow.com/questions/26955766/intellij-idea-checkstyle) plugin. Add configuration file from source directory. Set checkstyle version to 8.32.
And scan the files that you modify to fix all the checkstyle issues.

2021-09-02 05:00 UTC, Technoboy- requested changes

2021-09-02 05:00 UTC, Technoboy- commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
> +            //TopicDomain.persistent
Remove the comment

2021-09-02 05:00 UTC, Technoboy- commented on mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java
> +        //test default topic domaon for  non-persistent
domaon -> domain.

2021-09-02 05:00 UTC, Technoboy- commented on mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java
> +        //test default topic domaon for persistent
domaon -> domain.

2021-09-02 05:00 UTC, Technoboy- commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServerConfiguration.java
> +            doc = "Default Pulsar topic persistent that the MQTT server used."
Default Pulsar topic persistent -> Default Pulsar topic domain

2021-09-02 05:00 UTC, Technoboy- commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
> +            doc = "Default Pulsar topic persistent that the MQTT server used."
Default Pulsar topic persistent -> Default Pulsar topic domain

2021-09-02 08:53 UTC, Technoboy- commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
> +            doc = "Default Pulsar topic that the MQTT server used."
Default Pulsar topic that the MQTT server used -> Default Pulsar topic domain the MQTT server used.

2021-09-02 08:53 UTC, Technoboy- commented on mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServerConfiguration.java
> +            doc = "Default Pulsar topic that the MQTT server used."
Default Pulsar topic that the MQTT server used. -> Default Pulsar topic domain the MQTT server used.

2021-09-02 09:44 UTC, liangyuanpeng commented
```
Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 77.72 s <<< FAILURE! - in io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest
Error:  testBasicPublishAndConsumeWithMQTT(io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest)  Time elapsed: 60.015 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT() didn't finish within the time-out 60000
	at com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingPublishFlow.onCancel(MqttIncomingPublishFlow.java:183)
	at com.hivemq.client.internal.mqtt.handler.util.FlowWithEventLoop.cancel(FlowWithEventLoop.java:62)
	at com.hivemq.client.internal.mqtt.MqttBlockingClient$MqttPublishes.close(MqttBlockingClient.java:385)
	at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3BlockingClientView$Mqtt3PublishesView.close(Mqtt3BlockingClientView.java:215)
	at io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT(HiveMQIntegrationTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFO] Running io.streamnative.pulsar.handlers.mqtt.ProxyTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.453 s - in io.streamnative.pulsar.handlers.mqtt.ProxyTest
[INFO] Running io.streamnative.pulsar.handlers.mqtt.SimpleIntegrationTest
[INFO] Tests run: 39, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.587 s - in io.streamnative.pulsar.handlers.mqtt.SimpleIntegrationTest
[INFO] Running io.streamnative.pulsar.handlers.mqtt.BasicAuthenticationIntegrationTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.037 s - in io.streamnative.pulsar.handlers.mqtt.BasicAuthenticationIntegrationTest
[INFO] Running io.streamnative.pulsar.handlers.mqtt.ProxyTLSTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.168 s - in io.streamnative.pulsar.handlers.mqtt.ProxyTLSTest
[INFO] Running io.streamnative.pulsar.handlers.mqtt.TokenAuthenticationIntegrationTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.032 s - in io.streamnative.pulsar.handlers.mqtt.TokenAuthenticationIntegrationTest
[INFO] Running io.streamnative.pulsar.handlers.mqtt.TLSTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.426 s - in io.streamnative.pulsar.handlers.mqtt.TLSTest
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT(io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest)
Error:    Run 1: HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT:57 » ThreadTimeout Me...
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO] 
[INFO] 
Error:  Tests run: 96, Failures: 1, Errors: 0, Skipped: 0
```  

Seems like not about this PR.

2021-09-02 12:06 UTC, Technoboy- commented
> ```
> Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 77.72 s <<< FAILURE! - in io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest
> Error:  testBasicPublishAndConsumeWithMQTT(io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest)  Time elapsed: 60.015 s  <<< FAILURE!
> org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT() didn't finish within the time-out 60000
> 	at com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingPublishFlow.onCancel(MqttIncomingPublishFlow.java:183)
> 	at com.hivemq.client.internal.mqtt.handler.util.FlowWithEventLoop.cancel(FlowWithEventLoop.java:62)
> 	at com.hivemq.client.internal.mqtt.MqttBlockingClient$MqttPublishes.close(MqttBlockingClient.java:385)
> 	at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3BlockingClientView$Mqtt3PublishesView.close(Mqtt3BlockingClientView.java:215)
> 	at io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT(HiveMQIntegrationTest.java:57)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
> 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.ProxyTest
> [INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.453 s - in io.streamnative.pulsar.handlers.mqtt.ProxyTest
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.SimpleIntegrationTest
> [INFO] Tests run: 39, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.587 s - in io.streamnative.pulsar.handlers.mqtt.SimpleIntegrationTest
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.BasicAuthenticationIntegrationTest
> [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.037 s - in io.streamnative.pulsar.handlers.mqtt.BasicAuthenticationIntegrationTest
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.ProxyTLSTest
> [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.168 s - in io.streamnative.pulsar.handlers.mqtt.ProxyTLSTest
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.TokenAuthenticationIntegrationTest
> [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.032 s - in io.streamnative.pulsar.handlers.mqtt.TokenAuthenticationIntegrationTest
> [INFO] Running io.streamnative.pulsar.handlers.mqtt.TLSTest
> [INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.426 s - in io.streamnative.pulsar.handlers.mqtt.TLSTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> Error:  Failures: 
> Error:  io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT(io.streamnative.pulsar.handlers.mqtt.hivemq.HiveMQIntegrationTest)
> Error:    Run 1: HiveMQIntegrationTest.testBasicPublishAndConsumeWithMQTT:57 » ThreadTimeout Me...
> [INFO]   Run 2: PASS
> [INFO]   Run 3: PASS
> [INFO]   Run 4: PASS
> [INFO]   Run 5: PASS
> [INFO]   Run 6: PASS
> [INFO]   Run 7: PASS
> [INFO] 
> [INFO] 
> Error:  Tests run: 96, Failures: 1, Errors: 0, Skipped: 0
> ```
> 
> Seems like not about this PR.

Did you run successfully in your local ?

2021-09-03 02:31 UTC, liangyuanpeng commented
> testBasicPublishAndConsumeWithMQTT

Yes.  sometime  timeout.  

![testIntegration](https://user-images.githubusercontent.com/28711504/131941707-59eddb7a-5495-45ea-a2a4-0dd9364b8d6c.png)

2021-09-03 08:52 UTC, Technoboy- approved these changes
LGTM

2021-09-03 09:05 UTC, gaoran10 approved these changes
LGTM

2021-09-03 09:19 UTC, merged